version: 1.0.{build}
image: Visual Studio 2017
skip_commits:
  message: /^chore(release)/
branches:
  only:
  - master
  - /preview\/*/ 
  - /release\/*/
environment:
  publishtoken:
    secure: NEPxqNv122RRwPZLn9HGF4wld0VbuxFhXIjQMw8mYbkaSudpMQc1Yr2TqRc1uCvbbFfwMYVHu4/S2SfoXnrmmQ==
  GH_TOKEN: 
    secure: 0NJdORJRFjpB0dwUYv7bVNsbkldkoBhnvWik/CTOwAF/k9kP+/uTWMFnDcpEpt8E
install:
- cmd: npm install terser -g
- cmd: npm install replace-in-file -g
- cmd: npm i -g tfx-cli
- cmd: gitversion /l console /output buildserver
- ps: ./appveyorinit.ps1
build_script:
- cmd: >-
    cd pull-request-cz

    make.cmd
artifacts:
- path: pull-request-cz/dist/*vsix
  name: package
deploy:
for:
-
  branches:
    only:
    - master
  on_success:
  - cmd: >-
    tfx extension create --override "{\"version\": \"%SemVer%.%GitVersion_BuildMetaData%\"}" --overrides-file ..\override.json --output-path dist
  - ps: >-
      if (-Not $env:APPVEYOR_PULL_REQUEST_NUMBER) { 
        tfx extension publish --vsix dist\aguafrommars.cz-pull-request-$env:SemVer.$env:GitVersion_BuildMetaData.vsix --token $env:publishtoken
      }
-
  branches:
    only:
    - /release\/*/
  on_success:
  - ps: if (-Not $env:APPVEYOR_PULL_REQUEST_NUMBER) { tfx extension publish --vsix dist\aguafrommars.cz-pull-request-$env:SemVer.$env:GitVersion_BuildMetaData.vsix --token $env:publishtoken }
